name: Build and Distribute to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  call-pypi-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-pypi.yml@vreusable-pypi
    permissions:
      contents: read
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
